# Sources:
#  - https://telemetry.timseverien.com/
export NEXT_TELEMETRY_DISABLED=1
export GATSBY_TELEMETRY_DISABLED=1
export ASTRO_TELEMETRY_DISABLED=1
export NUXT_TELEMETRY_DISABLED=1
export STORYBOOK_DISABLE_TELEMETRY=1


