apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: redis-commander
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password | quote }}
