vim.api.nvim_set_keymap('n', 'ff', '<cmd>Telescope find_files find_command=rg,--files<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', 'fg', '<cmd>Telescope live_grep hidden=true<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', 'ss', ':vsplit<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', 'sf', ':split<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', 'tn', ':tabnew<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', 'tl', ':tabnext<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', 'th', ':tabprev<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>h', '<C-w>h', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>j', '<C-w>j', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>k', '<C-w>k', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>l', '<C-w>l', { noremap = true })
vim.api.nvim_set_keymap('n', '<C-n>', ':NvimTreeToggle<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', 'gs', ':Neogit<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>q', ':vertical resize +10<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>r', ':vertical resize -10<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>e', ':resize +10<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>w', ':resize -10<CR>', { noremap = true })
--vim.api.nvim_set_keymap('n', '<Leader>f', '<cmd>lua vim.lsp.buf.format()<CR>', { noremap = true })

vim.g['copilot_no_tab_map'] = true
vim.g['copilot_assume_mapped'] = true
vim.api.nvim_set_keymap('i', '<C-h>', 'copilot#Accept("<CR>")', { expr = true, silent = true })
