replicaCount: 1

image:
  repository: rediscommander/redis-commander
  tag: latest
  pullPolicy: IfNotPresent

  #service:
  #type: ClusterIP
  #name: redis-commander
  #port: 8081

service:
  type: NodePort
  name: redis-commander
  port: 8081
  nodePort: 30081 # Assign a fixed NodePort

resources: {}

redis:
  host: redis-master

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: redis-commander.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
